---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install dependencies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "create backend folder"
  shell:
    "mkdir ~/backend"

- name: "Copy files"
  template:
    src: files/artifact.tar.gz
    dest: ~/

- name: untar the the artifact
  become: yes
  shell: |
      tar -xvf archive.tar.gz -C ~/backend

- name: install node dependencies
  become: yes
  shell: |
      npm install
      pm2 stop default
      pm2 start npm -- start
  args:
    chdir: "~/backend"